Improves README for self-surface.
entropyxyz/cli pull request #100
Opened 2024-06-12 19:34 UTC by johnnymatthews

Closes https://github.com/entropyxyz/cli/issues/19

2024-06-12 20:46 UTC, rh0delta requested changes

2024-06-12 20:46 UTC, rh0delta commented on README.md
> +| Balance | Show the balance of any locally stored accounts. |
Balance shows only the free balance of the currently selected account, might want to change the wording on this one

2024-06-12 20:46 UTC, rh0delta commented on README.md
> +| User Programs | List the programs stored on the Entropy network by any locally stored accounts. |
same here the list of programs is for the currently selected account

2024-06-13 14:03 UTC, johnnymatthews commented on README.md
> +| Balance | Show the balance of any locally stored accounts. |
Yeah you're right. But I don't want to complicated this readme by getting into the whole _selecting an account_ thing. That's discussed over in the docs. For now, I reckon this content is fine.

2024-06-13 14:03 UTC, johnnymatthews commented on README.md
> +| User Programs | List the programs stored on the Entropy network by any locally stored accounts. |
Duplicated from [previous comment](https://github.com/entropyxyz/cli/pull/100#discussion_r1637064425):

> Yeah you're right. But I don't want to complicated this readme by getting into the whole _selecting an account_ thing. That's discussed over in the docs. For now, I reckon this content is fine.

2024-06-14 21:06 UTC, rh0delta approved these changes

2024-06-17 19:28 UTC, merged