Mixmix/test migration
entropyxyz/cli pull request #108
Opened 2024-06-13 06:41 UTC by mixmix

write tests over config + migrations

this is a base PR that I will extend the "move config" migration from

2024-06-14 20:25 UTC, rh0delta requested changes

2024-06-14 20:25 UTC, rh0delta commented on src/config/index.ts
> +import { /* statSync, */ readFileSync } from 'node:fs'
```suggestion
import { readFileSync } from 'node:fs'
```

2024-06-14 20:25 UTC, rh0delta commented on src/config/index.ts
> +// import { join } from 'path'
```suggestion
```

2024-06-18 02:41 UTC, mixmix commented
@rh0delta can you check this, and merge if all good?

2024-06-18 15:49 UTC, rh0delta approved these changes

2024-06-18 15:49 UTC, merged