balance testing
entropyxyz/cli pull request #130
Opened 2024-06-20 04:08 UTC by mixmix

WIP

Depends on : https://github.com/entropyxyz/sdk/pull/389

2024-06-20 04:11 UTC, mixmix commented
@rh0delta if you `yarn link` in that associated SDK PR ... then try to run the tests you will see:
```output
yarn run v1.22.1
$ yarn test:types && yarn test:ts && yarn test:only
$ tsc --project tsconfig.json
tests/balance.test.ts:4:21 - error TS2307: Cannot find module '@entropyxyz/sdk/keys' or its corresponding type declarations.

4 import Keyring from '@entropyxyz/sdk/keys'
                      ~~~~~~~~~~~~~~~~~~~~~~

tests/testing-utils/index.ts:1:49 - error TS2307: Cannot find module '@entropyxyz/sdk/dev/testing-utils.mjs' or its corresponding type declarations.

1 import { spinNetworkUp, spinNetworkDown, } from "@entropyxyz/sdk/dev/testing-utils.mjs"
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


```


I think the problem is our `moduleResoltion` in `tsconfig` .... like it's set to some old value `node` when it should be something newer? I dunno, it's a nightmare
https://stackoverflow.com/questions/70296652/how-can-i-use-exports-in-package-json-for-nested-submodules-and-typescript

2024-06-21 20:35 UTC, rh0delta commented
> @rh0delta if you `yarn link` in that associated SDK PR ... then try to run the tests you will see:
> 
> ```
> yarn run v1.22.1
> $ yarn test:types && yarn test:ts && yarn test:only
> $ tsc --project tsconfig.json
> tests/balance.test.ts:4:21 - error TS2307: Cannot find module '@entropyxyz/sdk/keys' or its corresponding type declarations.
> 
> 4 import Keyring from '@entropyxyz/sdk/keys'
>                       ~~~~~~~~~~~~~~~~~~~~~~
> 
> tests/testing-utils/index.ts:1:49 - error TS2307: Cannot find module '@entropyxyz/sdk/dev/testing-utils.mjs' or its corresponding type declarations.
> 
> 1 import { spinNetworkUp, spinNetworkDown, } from "@entropyxyz/sdk/dev/testing-utils.mjs"
>                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> I think the problem is our `moduleResoltion` in `tsconfig` .... like it's set to some old value `node` when it should be something newer? I dunno, it's a nightmare https://stackoverflow.com/questions/70296652/how-can-i-use-exports-in-package-json-for-nested-submodules-and-typescript

this has been fixed with edits made in the connected PR on the sdk repo https://github.com/entropyxyz/sdk/pull/389

2024-06-21 21:46 UTC, frankiebee requested changes
just commit my suggestions they docs @rh0delta

2024-06-21 21:46 UTC, frankiebee commented on src/common/initializeEntropy.ts
> +  return undefined
```suggestion
// explicitly return undefined so their is no confusion around what is selcted
  return undefined
```

2024-06-21 21:46 UTC, frankiebee commented on src/common/initializeEntropy.ts
> +    if (!accountData.seed && !accountData.admin) {
```suggestion
// check if their is no admin account and no seed so that we can throw an error
    if (!accountData.seed && !accountData.admin) {
```

2024-06-21 21:46 UTC, frankiebee commented on src/common/initializeEntropy.ts
> +    const storedKeyring = getKeyring(accountData?.admin?.address)
(non blocker) why? 😢

2024-06-21 21:46 UTC, frankiebee commented on src/common/initializeEntropy.ts
> +    const storedKeyring = getKeyring(accountData?.admin?.address)
because admin might not exist

2024-06-24 18:30 UTC, merged