[NayNay] Entropy Faucet
entropyxyz/cli pull request #133
Opened 2024-06-23 21:56 UTC by rh0delta

2024-07-26 17:01 UTC, rh0delta commented
recheck

2024-07-26 19:47 UTC, JesseAbram commented
I have read the CLA Document and I hereby sign the CLA

2024-07-26 19:48 UTC, JesseAbram commented
recheck

2024-07-29 23:53 UTC, mixmix commented
From team meeting:

**naynay**: last piece is getting test passing
file structure piece is more important

2024-08-26 18:09 UTC, frankiebee reviewed
Hey bud.... you know this will have to match the new file structure... i guess i'll still merge it into dev and you can restructure after.

2024-08-26 18:16 UTC, frankiebee requested changes

2024-08-28 18:29 UTC, rh0delta commented on dev/README.md
> +- faucet program from repo or tests/programs
```suggestion
- faucet program
  - build from repo or use binary in tests/programs/faucet_program.wasm
```

2024-08-28 18:47 UTC, frankiebee requested changes
One thing to change and then all good!

2024-08-28 18:47 UTC, frankiebee commented on src/flows/entropyFaucet/constants.ts
> +export const TESTNET_PROGRAM_HASH = '0x12af0bd1f2d91f12e34aeb07ea622c315dbc3c2bdc1e25ff98c23f1e61106c77'
```suggestion
// this is differnt from tests because the fauce that is live now was lazily deployed without schemas
// TO-DO: update this when faucet is deployed properly 
export const TESTNET_PROGRAM_HASH = '0x12af0bd1f2d91f12e34aeb07ea622c315dbc3c2bdc1e25ff98c23f1e61106c77'
```

2024-08-28 18:47 UTC, frankiebee commented on src/flows/entropyFaucet/faucet.ts
> +async function faucetSignAndSend (call: any, api: any, entropy: Entropy, amount: number, senderAddress: string, chosenVerifyingKey: any): Promise<any> {
dont pass `api` and `entropy`

2024-08-28 18:54 UTC, frankiebee approved these changes
great thanks!

2024-08-28 18:54 UTC, frankiebee commented on src/flows/entropyFaucet/faucet.ts
awesome thank you

2024-08-28 21:58 UTC, merged