[NayNay] Transfer updates + unit testing
entropyxyz/cli pull request #140
Opened 2024-06-26 18:09 UTC by rh0delta

closes #124

2024-07-01 21:30 UTC, mixmix commented on src/flows/entropyTransfer/transfer.ts
> +  const { from, to, amount } = payload
:hot_pepper: potential problems:
- `from` is optional any - does `signAndSend` care ?
- `amount` can be "dog" - does `transferAllowDeath` care ?

**Proposal** : I'd feel a lot safer if these unit-test level functions were **super tight**, i.e. I would have written the type

```ts
export interface TransferOptions { 
  from: string
  to: string
  amount: bigint 
}
```
Basically I'm noticing I don't trust Polkadot given past drama and my response to that is to (perhaps paranoid) nail everything down everywhere. This PR suggests a different approach, which may be fine to, but lets align on an approach we wanna all do (whatever it is)

2024-07-01 21:52 UTC, mixmix commented on src/common/initializeEntropy.ts
> +export function getKeyring (address?: string, seed?: string) {
:hot_pepper: this has technical debt creep vibes. Why would the `seed` be on the `accountData` while the `admin.address` is not?

Should this function ever be able to take nothing in? I feel like the real name of this function should be `getCachedKeyring` in which case being able to pass in no address/seed seems wrong to me (all your inputs are optional).

This is definitely a case of me being a pedant. 

**Proposal:**
1. given this function is ONLY used here, we remove the `export`
2. investigate why `accountData` could have a seed but no address? (different issue/ PR?)

2024-07-01 21:55 UTC, mixmix commented on src/config/index.ts
> +const paths = envPaths('entropy-cryptography', { suffix: '' })
:scream: this change is correct, but suggests there was a reversion of a commit I'd done?
Good catch, and also WTF is going on, am I crazy or is something about merge-squash messing up our history. I feel like this is not the first time we've had something like this go weird

2024-07-01 22:03 UTC, mixmix commented on src/flows/entropyTransfer/index.ts
> +    clearInterval(interval)
This needs to be called in every outcome, but if there is an error right now it will continue.
I propose extracting a function like

```js
function setupTransferProgress () {
  // ...
  const close = () => {
    clearInterval(interval)
    b1.stop()
  }
  return { close }
}
```

then you can call
```js
cons progress = setupTransferProgress()

// and later *everywhere* it's needed drop the stop e.g. 

catch (err) {
  progress.close()
}
```

2024-07-01 22:04 UTC, mixmix commented on src/flows/entropyTransfer/index.ts
> +    clearInterval(interval)
NOTE: this is not your fault, this is a gotcha I'm spotting and is a refactor.... if you want this could be an issue / PR raised that's seperate

2024-07-01 22:06 UTC, rh0delta commented on src/config/index.ts
> +const paths = envPaths('entropy-cryptography', { suffix: '' })
No issue with the commit history, this was my mistake. There was an issue found that didn't allow the cli to start and it was due to my machine not having the entropy-cryptography folder but having the entropyxyz directory. Mild oversight

2024-07-01 23:06 UTC, mixmix commented on tests/transfer.test.ts
> +  t.equal(charlieBalance, 1e21, 'charlie got bank')
:sunglasses:

2024-07-01 23:09 UTC, mixmix commented on tests/transfer.test.ts
> +  }
```suggestion
  const transferStatus = await run(
    'transfer',
    transfer(entropy, {
      from: charlieEntropy.keyring.accounts.registration.pair,
      to: recipientAddress,
      amount: BigInt(1000 * 10e10)
    })
  )
  // @ts-ignore
  t.true(transferStatus?.isFinalized, 'Funds transferred successfully')
```

2024-07-01 23:14 UTC, mixmix requested changes
Great clear test, some nice refactoring, couple suggested tweaks.

The only one I want us all to agree on is:
- https://github.com/entropyxyz/cli/pull/140/files#r1661560792 - how flexy are our atomic functions (team decision, I'll discuss with Frankie when I catch up with her)

The other one about `getKeyring` I'm happy to be flexible on, so long as you consider what I've said and thought about future cost of what you're changing

2024-07-02 17:11 UTC, rh0delta commented
@mixmix @frankiebee this is ready for re-review

2024-07-02 18:10 UTC, frankiebee commented on tests/testing-utils/setup-test.ts
> +import Keyring from '@entropyxyz/sdk/keys'
is their an an issue for this on sdk? this dosent look good. `why?`

2024-07-02 18:12 UTC, frankiebee approved these changes
Looks good to me! but will wait for @mixmix to re-review.

2024-07-03 02:29 UTC, mixmix commented on src/common/progress.ts
> +export function setupProgress (label: string): { start: () => void; stop: () => void } {
# :kissing_heart: 

It's beautiful

2024-07-03 02:32 UTC, mixmix commented on src/flows/entropyTransfer/types.ts
> +export interface TransferOptions {
# :heart_eyes:

2024-07-03 02:34 UTC, mixmix commented on tests/transfer.test.ts
> +// WIP: I'm seeing problems importing this?
Is it resolved in the SDK that is un-published yet I wonder

2024-07-03 02:35 UTC, mixmix approved these changes

2024-07-03 02:35 UTC, mixmix commented
Great work @rh0delta 
I'm gonna merge, and I've opened an issue for SDK types importing problems

2024-07-03 02:35 UTC, merged