[NayNay] File Restructure: Base Class + Balance Restructure
entropyxyz/cli pull request #207
Opened 2024-07-31 19:51 UTC by rh0delta

## Related Issue(s)

- Resolves #[issue_number]

## Proposed Changes

- created new base entropy class to handle the shared nature of the intended use of the class
- restructured balance to be in its own parent directory in the root of src
- created command and util file to contain pure functions and controller functions

## Testing

- [x] Unit tests added/updated
- [ ] Integration tests added/updated
- [ ] Manual testing performed

## Screenshots (if applicable)

## Additional Context

## Checklist

- [x] I have performed a self-review of my code.
- [ ] I have added tests.
- [x] I have commented my code.
- [ ] I have included a `CHANGELOG.md` entry.
- [ ] I have updated documentation in `github.com:entropyxyz/entropy-docs`, where necessary.

2024-07-31 20:22 UTC, frankiebee commented
notes from draft verbal review:
the base class should just be called `Base`
lets drop controller as a naming scheme

2024-07-31 20:35 UTC, frankiebee commented on src/balance/utils.ts
> +  }
im torn on this. I have reservations about not having a pure function here

2024-07-31 20:37 UTC, frankiebee requested changes

2024-07-31 20:37 UTC, frankiebee commented on src/balance/utils.ts
> +  }
acctually yeah change this. it dosent need to be a class that extends bas the command class should just pass entropy and this should be a pure function

2024-08-01 01:22 UTC, mixmix commented
I'm assuming this doesn't need more review from me @frankiebee ?

Anyone feel free to tag me back in if you want attention

2024-08-01 01:23 UTC, rh0delta commented
@mixmix would love your thoughts on this one, specifically the new file structure and the organization/use of the new files

2024-08-01 01:23 UTC, rh0delta commented
@frankiebee updated the utils to be pure functions, wanna re-review 😬

2024-08-01 02:10 UTC, mixmix requested changes
Good start to to restructure. I think we need that `flows/balance` folder gone to see how this is gonna land. I think this might end up then touching the root `cli.ts` and `tui.ts`.

And then the whole session concept ....phew

2024-08-01 02:10 UTC, mixmix commented on src/balance/command.ts
> +import { FLOW_CONTEXT } from "./constants"
Questions:
1. why did you split out utils?
    - is it because you don't want logger things in that level?
2. why is `FLOW_CONTEXT` extracted?
    - it seems like that's not gonna be used by anything else, so ... premature optimization
    - can you just put it as a `const` at the top of this file / in the constructor?

2024-08-01 02:10 UTC, mixmix commented on src/balance/command.ts
> +    return `${balance.toLocaleString('en-US')} BITS`
I really don't think this should have `BITS`, I don't even know about the `tolocaleString`.
We want this to be CLI first, so just raw JSON friendly formats like numbers, objects, **not** sentences (number + unit).

I could be wrong!

2024-08-01 03:03 UTC, rh0delta commented on src/balance/command.ts
> +import { FLOW_CONTEXT } from "./constants"
> Questions:
> 
> 1. why did you split out utils?
>    
>    * is it because you don't want logger things in that level?
> 2. why is `FLOW_CONTEXT` extracted?
>    
>    * it seems like that's not gonna be used by anything else, so ... premature optimization
>    * can you just put it as a `const` at the top of this file / in the constructor?

1. splitting out utils was a decision made to have one unified file that contains the pure functions for the individual command, and remove any idea about having to do anything but make the request to retrieve balance (in this case) and return that data. the removal of logging here was a decision made to allow the command class take care of the "business logic" as my corporate colleagues would call it, which includes error handling/logging and logging of generic information.
2. yeah it was kinda premature, i was under the impression there would be more shareable variables, and originally there was a use since we had the need for flow context in both the utils and command classes, but that has since changed so i will update and remove this file

2024-08-03 21:04 UTC, rh0delta commented on src/balance/command.ts
> +    return `${balance.toLocaleString('en-US')} BITS`
the utils method is the pure function that returns a number, my vision was that the controller/command file will handle how we want the data to be presented

2024-08-05 15:40 UTC, rh0delta commented
@mixmix got some time for a re-review on this one?

2024-08-05 17:16 UTC, frankiebee approved these changes

2024-08-05 17:17 UTC, merged