add deploy to CLI, including start of CLI refactor
entropyxyz/cli pull request #213
Opened 2024-08-01 04:56 UTC by mixmix

This adds deploy to the CLI

This PR also start to add a new pattern for how to CLI which is "one file per major command"
It shows how we're gonna do subcommands too

- [x] I have performed a self-review of my code.
- [N/A] I have added tests.
- [x] I have commented my code.
- [ ] I have included a `CHANGELOG.md` entry.
- [ ] I have updated documentation in `github.com:entropyxyz/entropy-docs`, where necessary.

2024-08-01 10:41 UTC, mixmix commented
@rh0delta I reckon the pattern here for cli could really help split out the tui/cli clutter.

2024-08-02 16:55 UTC, rh0delta commented
> @rh0delta I reckon the pattern here for cli could really help split out the tui/cli clutter.

Yeah i agree, i do like the degree of separation here, but will this be the same as how we want to handle the tui as well?

2024-08-21 05:01 UTC, mixmix commented on src/cli/commands/entropy-program.ts
> +      process.exit(0)
Lord. Good catch!

I think your point about extracting entropy instantiation is a good one. I can think of a nice way to do this I think. I was leaving that level of work out of this PR, but glad you've been working on that.

SO... checking proposed plan with this PR:
- you tell me where that "entropy initialization" refactor is
  - I help you get that branch merged into `dev` (if not already)
- I work on merging new `dev` into this PR?

2024-08-21 05:03 UTC, mixmix commented
I'm not sure how the TUI will end up....
I imagined functions that would call commands?

2024-08-22 04:38 UTC, mixmix commented on src/cli/commands/entropy-program.ts
> +      process.exit(0)
cc @rh0delta

2024-08-22 04:39 UTC, mixmix commented on src/cli/commands/entropy-program.ts
> +      process.exit(0)
oh you did show me that. I guess I want to help get those other PRs merged into `dev`

2024-08-22 21:34 UTC, mixmix commented
TODO:
- try merge in / rebase #219 
- if that doesn't work, just pull in the BaseCommand class

2024-08-22 22:03 UTC, mixmix commented on src/cli.ts
> +entropyProgramCommand(entropy, program) // WARNING this has been written to need access to entropy... but that's not defined yet?
@rh0delta TODO

2024-08-22 22:03 UTC, mixmix commented on src/cli.ts
> +  // If it is, then extract the hook fn, and loadEntropy out into src/common/utils-cli.ts
@rh0delta TODO

2024-08-22 22:04 UTC, mixmix commented on src/program/command.ts
> +import { deployProgram } from '../flows/programs/deploy'
NOTE: this PR was all about setting new pattern for CLI, so moving this into `main.ts` needs to be done later

2024-08-23 00:47 UTC, rh0delta commented on src/cli.ts
> +  // If it is, then extract the hook fn, and loadEntropy out into src/common/utils-cli.ts
the hook doesnt need to be on every command, just needs to sit at the root command `entropy` and it gets hit for every action

2024-08-23 16:26 UTC, rh0delta commented on src/cli.ts
> +entropyProgramCommand(entropy, program) // WARNING this has been written to need access to entropy... but that's not defined yet?
entropy gets defined once the cli is initialized, from the root entropy command hook

2024-09-19 04:58 UTC, rh0delta approved these changes

2024-09-22 22:50 UTC, mixmix commented on src/cli.ts
> +    // NOTE: on initial startup you have no account
YO so @rh0delta I had to change this bit cos on initial startup you have no account.
Tested it and it seems to handle it fine ... but do we need to review all the interactions to see if they handle 
"entropy undefined" fine. A couple I tested just said "he you need an account to proceed"

2024-09-22 22:51 UTC, mixmix commented on src/cli.ts
> +    // NOTE: on initial startup you have no account
I'm gonna merge and raise an issue

2024-09-22 22:51 UTC, mixmix commented on src/cli.ts
> +    // NOTE: on initial startup you have no account
after tests pass...

2024-09-23 05:32 UTC, mixmix commented
Hey @rh0delta can I have a re-review? 
In particular I changed the config handling because ... tests were failing and I didn't like how `get` was having side effects (note it was actually `getAndInitialize` ... which made it quite hard to test and work with.

Through some closer looking I discovered that `config.init` was not actually being called anywhere! Now it is

2024-09-23 05:34 UTC, mixmix commented on src/config/index.ts
>  }
Here is where I change `get` and `getSync` back to good ol' "one purpose" functions

2024-09-23 05:36 UTC, mixmix commented on src/cli.ts
> +    return config.init()
Here is where I ensure `config.init` is always called (I hope?).

This makes sure:
- there is a config in place for when `config.get` / config.getSync` are called
- migrations are run :facepalm:

2024-09-23 05:38 UTC, mixmix commented on src/common/utils-cli.ts
> +
I found this file was the only place `config.getSync` was used. I decided to write a special function to catch any errors and then carefully handled all the cases where it comes back `null`

2024-09-23 16:16 UTC, rh0delta commented on src/cli.ts
> +  // )
this option will be used for the faucet, may not want to remove it right now.

2024-09-23 16:17 UTC, rh0delta commented on src/cli.ts
> +program.parseAsync()
the chained method was a recommendation by commander, why is it being removed?

2024-09-23 16:22 UTC, rh0delta requested changes
couple of questions, and some changes may be needed, otherwise looks good so far

2024-09-23 17:45 UTC, rh0delta commented
> Hey @rh0delta can I have a re-review? In particular I changed the config handling because ... tests were failing and I didn't like how `get` was having side effects (note it was actually `getAndInitialize` ... which made it quite hard to test and work with.
> 
> Through some closer looking I discovered that `config.init` was not actually being called anywhere! Now it is

How was it that config.init was never called? really curious about this. I thought we had it initialized at the same point as initializing wasm.

2024-09-24 03:52 UTC, mixmix commented on src/cli.ts
> +program.parseAsync()
because it doesn't do anything.
:heavy_check_mark: if it works don't fix it!
:heavy_check_mark: prune dead code?

# :scream: 

not sure which wins. This has been annoying me for a while tho

2024-09-24 04:04 UTC, rh0delta commented on src/cli.ts
> +program.parseAsync()
If there is no significant impact to removing it, I'm cool with it being gone. Have you tested the programmatic cli without the chained method?

2024-09-24 04:12 UTC, mixmix commented on src/cli.ts
> +  // )
reverted!

2024-09-24 04:13 UTC, mixmix commented on src/cli.ts
> +program.parseAsync()
yes!

2024-09-24 04:16 UTC, mixmix commented
Yeah I don't know what happened! I assume it just got lost in the refactoring.

2024-09-24 04:17 UTC, mixmix commented on src/program/command.ts
> +    // .addCommand(entropyProgramList())
I wanna do these in a different PR. Maybe even after we do a new release.
This is "feature completeness", not "refactor"

2024-09-24 04:19 UTC, mixmix commented on src/program/main.ts
> +  }
NOTE: I think these are about to change with the next SDK release (just reviewing these)

2024-09-24 04:20 UTC, rh0delta approved these changes

2024-09-24 04:34 UTC, merged