[NayNay] File Restructure: Accounts Restructure
entropyxyz/cli pull request #215
Opened 2024-08-05 17:25 UTC by rh0delta

## Related Issue(s)

- Resolves #210 

## Proposed Changes

- refactoring file structure + flow of accounts in cli/tui

## Testing

- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [ ] Manual testing performed

## Screenshots (if applicable)

## Additional Context

## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have added tests.
- [ ] I have commented my code.
- [ ] I have included a `CHANGELOG.md` entry.
- [ ] I have updated documentation in `github.com:entropyxyz/entropy-docs`, where necessary.

2024-08-22 00:05 UTC, mixmix requested changes
Looking good. Scope creep means you get some annoying questions sorry :cry: 
I have not got to the end of reviewing this. Keen to pause here and review again once other things have been resolved to catch any final minor gotchas

2024-08-22 00:05 UTC, mixmix commented on src/cli.ts
> +  )
:fire: this was not really designed yet.

Questions that need considering:
1. how do you specify multiple programs+configs
2. does this need to take a name?
3. what is program data? I think you mean programConfig  right? I'd like to see consistent language whatever it is.

Other notes
- I think it should be `-p, --pointer` (the short-code should be short, not just the same word)


NOTE: lack of design for this means we can choose to:
1. merge this, then break it later (pain)
2. do the just in time design now, slow this PR down (pain)
3. rip out this work (pain)

2024-08-22 00:05 UTC, mixmix commented on src/common/utils.ts
> +export async function updateConfig (storedConfig: EntropyConfig, newUpdates: any) {
what does the return value mean? why true / false

2024-08-22 00:05 UTC, mixmix commented on src/cli.ts
> +    await updateConfig(storedConfig, { accounts, selectedAccount: updatedAccount.address })
there are multiple `updateConfig` floating around with different signatures? can we collapse into using just the one please?

2024-08-22 16:45 UTC, rh0delta commented on src/cli.ts
> +  )
might have to use -po or something as -p is being used by password i believe

2024-08-22 21:24 UTC, mixmix commented on src/accounts/command.ts
> +export class AccountsCommand extends BaseCommand {
- `EntropyAccount`
- move to `src/account/main.ts`  (not folder rename)

2024-08-22 21:25 UTC, mixmix commented on src/accounts/command.ts
> +  public async runInteraction (config): Promise<any> {
move to this out to `src/account/interaction.ts`

2024-08-22 21:27 UTC, mixmix commented on src/accounts/utils.ts
> +export const newAccountQuestions = [
_could_ live in new `src/account/interaction.ts`

2024-08-28 22:00 UTC, rh0delta commented on src/account/command.ts
> +//   })
commented out for now to give time for a better design of programmatic registrations

2024-08-28 23:09 UTC, rh0delta commented on src/account/main.ts
> +        'Accounts Error: There are currently no accounts available, please create or import a new account'
```suggestion
        'AccountsError: There are currently no accounts available, please create or import a new account using the Manage Accounts feature'
```

2024-08-28 23:13 UTC, rh0delta commented on tests/manage-accounts.test.ts
> +    t.equal(msg, 'AccountsError: There are currently no accounts available, please create or import your new account using the Manage Accounts feature')
```suggestion
    t.equal(msg, 'AccountsError: There are currently no accounts available, please create or import a new account using the Manage Accounts feature')
```

2024-08-29 04:16 UTC, rh0delta commented on src/account/command.ts
> +}
Why do we want to split these commands up? They do the same things aside from import taking in a seed from user input

2024-08-29 04:54 UTC, rh0delta commented on tests/account.test.ts
>    const testAccountName = 'Test Account'
Need to move line 68 above line 67, tests are failing

2024-08-29 20:19 UTC, rh0delta commented on src/common/utils.ts
> +export async function updateConfig (storedConfig: EntropyConfig, newUpdates: any) {
the return value is a boolean as it sets the returnToMainMenu var to decide whether or not to ask if the user wants to return or if they should return to the main menu automatically

2024-09-16 21:25 UTC, frankiebee commented on tests/transfer.test.ts
>  // @ts-ignore
why?!

2024-09-17 03:03 UTC, mixmix commented on tests/transfer.test.ts
>  // @ts-ignore
yeah it sucks. I have a bad feeling the "export types" is a TS@latest feature D:

2024-09-17 03:07 UTC, mixmix commented on src/balance/command.ts
> +      const entropy = await loadEntropy(address,opts.endpoint)
```suggestion
      const entropy = await loadEntropy(address, opts.endpoint)
```

2024-09-17 03:07 UTC, rh0delta commented on tests/transfer.test.ts
>  // @ts-ignore
The ts-ignore has been removed and so far no issues have been seen, so I think we are good to not need it anymore. However, you will notice we are force casting to certain types, but that is due to not having types available from the SDK currently.

2024-09-17 03:13 UTC, mixmix commented on src/config/index.ts
> +    writeFileSync(configPath, '{}')
:fire: paranoid part of me says "You need to check you're only doing this if file doesn't exist" ... cos if it was some error, and there were keys in there.... you just wiped them

2024-09-17 03:17 UTC, rh0delta commented on src/config/index.ts
> +    writeFileSync(configPath, '{}')
Yeah makes sense to conditionally handle the file doesn't exist error

2024-09-17 04:40 UTC, mixmix requested changes
# MORE REVIEWS

2024-09-17 04:40 UTC, mixmix commented on src/account/command.ts
> +      cliWrite("Your address" + updatedAccount.address + "has been successfully registered.")
Design: I think it's want the account state returned - show me the programs + configs please?

2024-09-17 04:40 UTC, mixmix commented on src/account/command.ts
> +      cliWrite("Your address" + updatedAccount.address + "has been successfully registered.")
Is this a new feature? (could disable this an open an issue to design + implement?)

2024-09-17 04:40 UTC, mixmix commented on src/account/interaction.ts
> +export async function entropyManageAccounts (endpoint: string, storedConfig: EntropyConfig) {
```suggestion
export async function entropyAccount (endpoint: string, storedConfig: EntropyConfig) {
```

2024-09-17 04:40 UTC, mixmix commented on src/account/interaction.ts
> +    accounts.push(newAccount)
edge cases:
- try to make an account with same `name` as an existing account
- try to make an account with same `seed` as an existing account

both should fail rather than make a duplicate?

=> open issue?

2024-09-17 04:40 UTC, mixmix commented on src/account/interaction.ts
> +    accounts.push(newAccount)
in `command.ts` I wrote a function called `persistAndSelectNewAccount` which handles some of this.... could be it's a `util.ts`

2024-09-17 04:40 UTC, mixmix commented on src/common/entropy-base.ts
> +  constructor ({ entropy, endpoint, flowContext }: { entropy?: Entropy, endpoint: string, flowContext: string }) {
why is `entropy` optional? I thought we dropped need for that when we started using `static` methods for `EntropyAccount`

```suggestion
  constructor ({ entropy, endpoint, flowContext }: { entropy: Entropy, endpoint: string, flowContext: string }) {
```

2024-09-17 04:40 UTC, mixmix commented on src/common/utils-cli.ts
> +  // TODO
This is done?

```suggestion
```

2024-09-17 04:40 UTC, mixmix commented on src/common/utils.ts
> +export async function updateConfig (storedConfig: EntropyConfig, newUpdates: any) {
Please leave more comments around this. This function is a shapeshifter in that `newUpdates` is "any" ...

it's actually `"exit" | updates | undefined` right?
Maybe also make typescript show it returns a boolean and leave a note about what the boolean means `true means exit` ... but then why they fuck are we even going into this function, can't we check outside this ... this function is about `updateConfig` not `updateConfigIfItsConfigYouGaveMe` right?

yeah either the smells careful need notes, or tidying up please

2024-09-17 04:40 UTC, mixmix commented on src/account/command.ts
> +    )
:fire: I think this is wrong?

I think the options are:
- `programModAddress` <<
- `programData`

2024-09-17 04:40 UTC, mixmix commented on src/cli.ts
> +  return entropy
```suggestion
  return entropy
```

2024-09-17 04:40 UTC, mixmix commented on src/cli.ts
> +  let entropy: Entropy = entropyGlobal
:fire: the function had be modified to `set local entropy` within function (never modify `entropyGlobal`). I think it was a mistake and should be:

```suggestion
let entropy: Entropy
async function setEntropyGlobal (address: string, endpoint: string, password?: string) {
  console.log('args', address, endpoint, password);

```

2024-09-17 04:40 UTC, mixmix commented on src/cli.ts
> +    // console.log('entropy global in hook', entropyGlobal);
:fire: wait are we even using this any more?

2024-09-17 04:40 UTC, mixmix commented on src/cli.ts
> +    // console.log('entropy global in hook', entropyGlobal);
entropyGlobal that is

2024-09-17 16:12 UTC, rh0delta commented on src/account/main.ts
> +  async registerAccount (account: EntropyAccountConfig, registerParams?: AccountRegisterParams): Promise<EntropyAccountConfig> {
the use of the account here is for when we add the verifying key to the list of keys in the account, which will then be used to update the user's config

2024-09-17 16:16 UTC, rh0delta commented on src/account/command.ts
> +    )
removing the options for now until we update both the cli and tui to accept program configs

2024-09-17 16:18 UTC, rh0delta commented on src/cli.ts
> +    // console.log('entropy global in hook', entropyGlobal);
it was being used for the tui

2024-09-17 16:47 UTC, rh0delta commented on src/account/main.ts
> +          print('Successfully pruned registration');
updated to remove printing message

2024-09-17 21:35 UTC, mixmix commented on src/account/main.ts
> +        await this.pruneRegistration()
inline comment please about what this is / why

2024-09-17 21:39 UTC, mixmix commented on src/cli.ts
>      await setEntropyGlobal(address, endpoint, password)
If this is just used for TUI, move this into the TUI action ... maybe just pass it in as an argument

2024-09-17 21:41 UTC, mixmix commented on src/common/entropy-base.ts
> +  constructor ({ entropy, endpoint, flowContext }: { entropy?: Entropy, endpoint: string, flowContext: string }) {
BOOP

2024-09-18 03:59 UTC, mixmix commented on src/account/command.ts
> +      cliWrite("Your address" + updatedAccount.address + "has been successfully registered.")
done in another PR

2024-09-18 03:59 UTC, mixmix commented on src/account/interaction.ts
> +export async function entropyManageAccounts (endpoint: string, storedConfig: EntropyConfig) {
done in another PR

2024-09-18 04:25 UTC, mixmix commented on src/account/interaction.ts
> +    accounts.push(newAccount)
done in another PR

2024-09-18 04:27 UTC, mixmix commented on src/account/main.ts
> +        await this.pruneRegistration()
done in another PR

2024-09-18 04:27 UTC, mixmix commented on src/cli.ts
>      await setEntropyGlobal(address, endpoint, password)
done in another PR

2024-09-18 04:29 UTC, mixmix commented on src/common/entropy-base.ts
> +  constructor ({ entropy, endpoint, flowContext }: { entropy?: Entropy, endpoint: string, flowContext: string }) {
done in another PR

2024-09-18 04:30 UTC, mixmix commented on src/common/utils-cli.ts
> +  // TODO
done in another PR

2024-09-19 00:34 UTC, mixmix commented
# :heavy_check_mark: MERGE!!!!

2024-09-19 00:34 UTC, merged