[NayNay] File Restructure: Signing Restructure
entropyxyz/cli pull request #218
Opened 2024-08-07 20:43 UTC by rh0delta

## Related Issue(s)

- Resolves #212 

## Proposed Changes

- created new file structure for signing flow
- updated tui/cli with new changes

## Testing

- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [ ] Manual testing performed

## Screenshots (if applicable)

## Additional Context

## Checklist

- [x] I have performed a self-review of my code.
- [ ] I have added tests.
- [ ] I have commented my code.
- [ ] I have included a `CHANGELOG.md` entry.
- [ ] I have updated documentation in `github.com:entropyxyz/entropy-docs`, where necessary.

2024-08-21 23:23 UTC, mixmix requested changes
I love the direction and how you've split out `commands` + `types` + `utils` really clearly.

I've listed quite a few smallish things. Sorry it was 2 weeks and now a bunch of change requests, appreciate that might land a bit annoying.
Happy to have a call if you wanna connect + discuss anything (nicer way to resolve opinions sometimes, and can be faster)

2024-08-21 23:23 UTC, mixmix commented on src/signing/command.ts
> +  public async runInteraction (inquirer) {
I would like to not see Tui mixed in with CLI commands. I thought commands meant "commands that are called by the CLI"

I am keen on CLI commands being:
- the primary thing
- individual functions where the CLI names map pretty directly into our command functions
    - e.g. CLI  `entropy-sign arg1 arg2` => Function `entropySign.default(arg1, arg2)`
    - hmmm interesting , this doesn't really work that well as this one doesn't have a sub-command like other commands. hence suggesting calling it `default` (or something similar?) 

ANYWAY - I'd strongly like to see TUI stuff remove from this file so that it is forever and always a _consumer_ of the CLI commands. Then there can be no accidental problems, and `inquirer` doesn't need to be an argument?

2024-08-21 23:23 UTC, mixmix commented on src/signing/command.ts
> +import Entropy from "@entropyxyz/sdk"
Overall, LOVE the pattern this file sets up

2024-08-21 23:23 UTC, mixmix commented on src/signing/utils.ts
> +    result = readFileSync(msgPath, 'utf-8')
:fire: again, recommend revert.

Problem: What if the file is not utf-8 encoded and is e.g. an `.mp3` file. I *think* this needs some design

2024-08-27 03:46 UTC, mixmix requested changes
## Review 2.

Looking good. There are a few things that are style things (like I want the core functionality all in the `main.ts` file, not hidden elsewhere, and variable renames), and there are also so gotchas which will cause problems :fire: 

The scope creep with new features is starting to burn a bit much.
- I don't want to say again that `msg/msgPath` doesn't work needs more design
- `rawSign` is also new (I think)

**please revert these**. We need this mega branch merged and I don't want to stop to discuss those things :pray: :heart: 
I am real happy to revisit those as simple little side quests after this is merged

---

NOTE: this PR currently doesn't work with fresh installs!  (no accounts = no default selected nor selectable account = throws)

2024-08-27 03:46 UTC, mixmix commented on src/signing/command.ts
> +    .argument('msg', 'Message or Path to Message you would like to sign')
:fire: this is not feasible. Or rather I cannot see a way you can **know** whether a string is for a path or the actual message content. Examples
- `.env`
- `id_ed25519.pub`
- `https://matou.nz`

Please just make it one or the other `msgPath` or `msg`, not both.
Probably open a design issue too?

2024-08-27 03:46 UTC, mixmix commented on src/signing/command.ts
> +      if (opts.accountAddress) {
:fire: with `commander` I think it's `opts.account`  (it pays attention to `--account` not `<accountAddress>` ? which is weird to me but I think I tested it and was like "oh dang what?"

2024-08-27 03:46 UTC, mixmix commented on src/signing/constants.ts
> +export const FLOW_CONTEXT = 'ENTROPY_SIGNING'
Still relevant.
Want the folder to reflect the command name (sign, not signing)

2024-08-27 03:46 UTC, mixmix commented on src/signing/interaction.ts
> +    const auxiliaryData = JSON.parse(readFileSync(auxiliaryDataFile).toString())
I think this is the same?

```suggestion
    const auxiliaryData = JSON.parse(readFileSync(auxiliaryDataFile, 'utf-8'))
```

2024-08-27 03:46 UTC, mixmix commented on src/signing/main.ts
> +export class EntropySign extends EntropyBase {
:fire: please remove the knowledge of `msgPath` from this class. Do that processing upstream, all this class should care about is signing messages that have been passed in.

We want to contain knowledge about all that to one area only, not spread it across layers of our stack.

2024-08-27 03:46 UTC, mixmix commented on src/signing/main.ts
> +  }
I this a new feature? => out of scope

If it's in scope, then I want to see it:
- [ ] plugged into CLI (currently it's commented out)
- [ ] tested

```suggestion
```

2024-08-27 03:46 UTC, mixmix commented on src/signing/utils.ts
> +}
move these into `main.ts` please
I'd like to see our tests calling on `main.ts` as that is kinda designed to be the backbone of all our workflows.
I want to know CLI + TUI work with what they are calling (`main.ts` functions)

2024-08-27 03:46 UTC, mixmix commented on src/transfer/main.ts
> +    const { start: startProgress, stop: stopProgress } = setupProgress('Transferring Funds')
:fire: we can't have progress in the programmatic CLI - that could be used in programs which are reading the output of the command. Move this to the TUI

2024-08-27 03:46 UTC, mixmix commented on src/transfer/command.ts
> +    .action(async (_source, destination, amount, opts) => {
:fire::fire::fire::fire::fire: why do you drop the `source` here ... if I put in that I wanted to move funds from `A => B` and instead it moved from `selectedAccount => B` I would be wild mad.

so this might need more design... as the options I can see are:
- A. remove `source`
- B. require `source` but then ... have that override the `selectedAccount`   (error if `--account` is provided too?)

2024-08-27 03:46 UTC, mixmix commented on src/transfer/utils.ts
>  export async function transfer (entropy: Entropy, payload: TransferOptions): Promise<any> {
Please move this into `main.ts`

2024-08-27 03:47 UTC, mixmix commented on src/signing/command.ts
> +  public async runInteraction (inquirer) {
discussed on call, resolved

2024-08-27 19:30 UTC, rh0delta commented on src/transfer/utils.ts
>  export async function transfer (entropy: Entropy, payload: TransferOptions): Promise<any> {
why?

2024-08-27 19:34 UTC, rh0delta commented on src/transfer/command.ts
> +    .action(async (_source, destination, amount, opts) => {
the source in this case must be a funded entropy account, since we require the signer pair, not just an address. The source in this case must be provided by the selected account from the config which can be overrided by the current account address option, so i dont see the need for a specific source argument here

2024-08-27 21:26 UTC, mixmix commented
TODO:
- fix `loadEntropy`
- final review

2024-08-28 00:38 UTC, mixmix commented on src/common/utils-cli.ts
> +export async function reloadEntropy (entropy: Entropy, newAddress: string, oldAddress: string, endpoint: string): Promise<Entropy> {
resolved: https://github.com/entropyxyz/cli/pull/220

2024-08-28 00:38 UTC, mixmix commented on src/common/utils-cli.ts
> +    }
resolved: https://github.com/entropyxyz/cli/pull/220

2024-08-28 21:36 UTC, mixmix commented on src/balance/command.ts
> +      cliWrite(`${balance.toLocaleString('en-US')} BITS`)
I don't know if we want ` BITS` in there... but lets merge and see

2024-08-28 21:40 UTC, mixmix commented on src/sign/command.ts
> +  signCommand.command('sign')
:fire: this is a bug I named in the last review. I'm gonna fix it myself

TL;DR you have defined a cli command `entropy sign sign ...`

2024-08-28 22:28 UTC, mixmix commented on src/sign/command.ts
> +      cliWrite(`Signature: ${signature}`)
Discussed on call - we're gonna make this an object output

2024-08-28 23:00 UTC, mixmix commented on src/transfer/main.ts
> +  public async sendTransfer (toAddress: string, amount: string, startProgress?: ()=>void, stopProgress?: ()=>void) {
This feels like `interaction` to me... I don't understand why it exists - if the progress things are optional then this wrapper only does
- formatting `amount`
- logging


I think logging should be in the base `transfer` anyway ...

2024-08-28 23:02 UTC, mixmix approved these changes
YUSSS. I'm gonna make minor changes then merge

2024-08-28 23:06 UTC, mixmix commented on src/sign/command.ts
> +  signCommand.command('sign')
DONE

2024-08-28 23:06 UTC, mixmix commented on src/sign/command.ts
> +      cliWrite(`Signature: ${signature}`)
done

2024-08-28 23:58 UTC, mixmix commented on src/transfer/main.ts
> -      }
Dropped this check as `rawTransfer` only ever resolves if `isFinalized === true` already

2024-08-28 23:59 UTC, mixmix commented on tests/transfer.test.ts
> +    TransferService.transfer(naynayAddress, inputAmount)
Testing the actual "main" function we're using with the input it will be receiving (e.g. `"1.5"` as a string)

2024-08-29 00:00 UTC, mixmix commented on src/transfer/main.ts
> +    const formattedAmount = BigInt(Number(amount) * 1e10)
YO! the `parseInt` here was rounding our inputs.
Also what is our name for this `1e10`   ... is that that number of decimal places we support?

2024-08-29 00:44 UTC, merged