[NayNay] New SDK RC integration
entropyxyz/cli pull request #262
Opened 2024-10-18 20:39 UTC by rh0delta

## Related Issue(s)

- Resolves #[issue_number]

## Proposed Changes

- wip: integrating new sdk with new core changes

## Testing

- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [ ] Manual testing performed

## Screenshots (if applicable)

## Additional Context

## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have added tests.
- [ ] I have commented my code.
- [ ] I have included a `CHANGELOG.md` entry.
- [ ] I have updated documentation in `github.com:entropyxyz/entropy-docs`, where necessary.

2024-10-22 00:06 UTC, rh0delta commented on tests/faucet.test.ts
> +  const { run, entropy, endpoint } = await setupTest(t, { seed: eveSeed })
@mixmix change to use eve entropy for faucet made here

2024-10-22 02:16 UTC, mixmix commented on src/common/utils-cli.ts
> +
:fire: This looks a lot like if you open the cli ... you send a signal to jump-start the network?!

I'm gonna go try read docs on what that does...

2024-10-22 03:05 UTC, mixmix commented on tests/account.test.ts
> +  await run('transferring funds', transferService.transfer(naynay.keyring.accounts.registration.address, "1000"))
I think the setup should be extracted (set up of a funded account).

2024-10-22 03:05 UTC, mixmix commented on tests/account.test.ts
> +  await run('transferring funds', transferService.transfer(naynay.keyring.accounts.registration.address, "1000"))
Done here https://github.com/entropyxyz/cli/pull/263

2024-10-22 03:06 UTC, mixmix requested changes
see :fire: :point_up:

2024-10-22 16:29 UTC, rh0delta commented on src/common/utils-cli.ts
> +
yeah i agree this may not be the best place to trigger the jumpstart. need to find a better way to trigger the jumpstart when the network boots up

2024-10-23 00:50 UTC, mixmix commented on src/cli.ts
> +  .addOption(endpointOption())
:fire: you cannot do this

There is a problem with Commander where if you put this here then when someone calls e.g. `entropy balance --endpoint url` then there are two options - this one, and the one attached at the root level `entropy --endpoint url`

and they will get smooshed and over-write each other. This was a bad bug I caught the other day.

This is so spicy I made an issue: https://github.com/entropyxyz/cli/issues/265

2024-10-23 00:50 UTC, mixmix commented on src/cli.ts
> +  .addOption(endpointOption())
MUST be removed for now

```suggestion
```

2024-10-23 00:52 UTC, mixmix commented on src/common/utils.ts
> +    .signAndSend(entropy.keyring.accounts.registration.pair)
I am skeptical this promise actually waits for the jump-start to be done?
Should this be wrapped in `new Promise` with the event-listener which resolves the promise on `isFinalized` event or something?

2024-10-23 00:56 UTC, mixmix commented on src/tui.ts
> +        .catch(err => console.error('There was an issue jumpstarting the network', err))
I think this could use a a nice spinner thingee... if you felt like it

2024-10-23 15:58 UTC, rh0delta commented on src/cli.ts
> +  .addOption(endpointOption())
hmm, if that is the case then there is an even bigger issue at hand. If a user decides to use the TUI and wants to use a custom endpoint of their choosing they won't be able to. What do you think about creating a new endpoint option specific for this command? that way there is no overlap. We could also add some logic to determine which is the right option to use if there is a conflict between two of the same options attached to different commands?

2024-10-23 21:36 UTC, mixmix commented on src/common/utils-cli.ts
> +    .env('ENTROPY_ENDPOINT')
```suggestion
    .env('ENTROPY_TUI_ENDPOINT')
```

2024-10-24 00:57 UTC, merged