[NayNay] Updating Units within Entropy
entropyxyz/cli pull request #306
Opened 2024-11-13 01:57 UTC by rh0delta

## Related Issue(s)

- Resolves #221 

## Proposed Changes

- it had come to our attn that we were using the wrong units for the tokens display
- we were under the impression that bits were the smallest unit of the entropy token, that was a mistake
- updated all mentions of tokens and bits to match their respective definition
- updated return of balance to the human readable format, using BITS
- added new method to grab token details from chain

## Testing

- [x] Unit tests added/updated
- [ ] Integration tests added/updated
- [x] Manual testing performed

## Screenshots (if applicable)

## Additional Context

- needs changelog
- needs documentation update

## Checklist

- [x] I have performed a self-review of my code.
- [ ] I have added tests.
- [x] I have commented my code.
- [ ] I have included a `CHANGELOG.md` entry.
- [ ] I have updated documentation in `github.com:entropyxyz/entropy-docs`, where necessary.

2024-11-13 22:06 UTC, mixmix requested changes
Few things to address. 

Also needs
- [x] CHANGELOG entry
- [ ] README entry - saying all Inputs/ Outputs are in BITS (are they?)
- [x] another PR/ Issue about supporting flags like `--tokens` which sees output come out in raw tokens?

2024-11-13 22:10 UTC, rh0delta commented on src/balance/command.ts
> +      cliWrite(`${balance} ${symbol}`)
the out put is the same as it was before the change, this change is mainly to display the human readable amount as well as pull the symbol from the chain. not sure what youre 🔥 is referring too.

2024-11-13 22:12 UTC, rh0delta commented on src/common/utils.ts
> +}
this call takes about less than a 100 milliseconds, but im cool with caching the result

2024-11-13 22:15 UTC, rh0delta commented on src/common/utils.ts
> +}
i agree the tokensToBits should be a raw output and not perform the rounding. will make that change. the rounding can just happen on output for balance only i guess

2024-11-13 22:27 UTC, rh0delta commented on src/balance/command.ts
> +      cliWrite(`${balance} ${symbol}`)
if BITS needs to be removed, that's fine, but  wouldn't that cause confusion if users don't know what the number represents?

2024-11-13 22:58 UTC, rh0delta commented
@mixmix here is the issue for tracking the readme/docs update https://github.com/entropyxyz/entropy-docs/issues/261

2024-11-18 14:27 UTC, johnnymatthews commented
Associated docs issue: https://github.com/entropyxyz/entropy-docs/issues/265

2024-11-20 01:28 UTC, mixmix commented on src/balance/command.ts
> +      cliWrite(`${balance} ${symbol}`)
Yeah the :fire: was because `"1.234 BITS"` is kinda a pain to use in other scripts. e.g. if I write a script which moves all my balance to another account I cannot take the results of `balance` and put them into `transfer` ... because balance is not giving numbers, it's giving numbers and letters and a space. So it forces me to write some awk or something.

I think if you want the unit, you should have `--show-units` in the command? CLI commands are meant to be easy to chain IMO.

2024-11-20 01:28 UTC, mixmix commented on src/balance/command.ts
> +      cliWrite(`${balance} ${symbol}`)
If it feels like a different issue I'm raising (and it might well be), please open a new issue, put it in a milestone and mark this resolved.

2024-11-20 01:29 UTC, mixmix commented on src/faucet/interaction.ts
> +// 2 BITS
Probably the `comment and `amount` below it

2024-11-20 01:42 UTC, mixmix commented on CHANGELOG.md
> +>>>>>>> dev
```suggestion
- Shared
  - amount units are now correct! [#306](https://github.com/entropyxyz/cli/pull/306)
    - 1 nanoBITS = 0.00000000001 BITS
    - 1 BITS = 10000000000 nanoBITS
```

2024-11-20 01:43 UTC, mixmix commented on CHANGELOG.md
> +>>>>>>> dev
more merge conflict jank

2024-11-20 01:46 UTC, rh0delta commented on src/faucet/interaction.ts
> +// 2 BITS
Unable to change the value sent to transfer as it requires we send the bigint nanoBITS otherwise it doesn't send the value you expect.

2024-11-20 02:56 UTC, mixmix commented on src/transfer/command.ts
> +      cliWrite(`Transaction successful: Sent ${amount} ${symbol} to ${destination}`)
This fails the test "can this be parsed by another program easily"? If it's a human sentence then no it can't.

I'd propose this is out of scope / you should write out `{ bits: amount, source, destination }` ?

2024-11-21 19:30 UTC, rh0delta commented on CHANGELOG.md
> +>>>>>>> dev
fixed in latest commit

2024-11-21 19:30 UTC, rh0delta commented on CHANGELOG.md
> +>>>>>>> dev
fixed in latest commit

2024-11-21 19:32 UTC, rh0delta commented on src/transfer/command.ts
> +      cliWrite(`Transaction successful: Sent ${amount} ${symbol} to ${destination}`)
fixed it anyways, i see where youre coming from

2024-12-03 03:06 UTC, mixmix approved these changes
NICE!

2024-12-03 03:06 UTC, merged