[NayNay] Balance --all
entropyxyz/cli pull request #310
Opened 2024-11-14 19:27 UTC by rh0delta

## Related Issue(s)

- Resolves #305

## Proposed Changes

- updated balance command with an option to view all balances of accounts in the config

## Testing

- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [ ] Manual testing performed

## Screenshots (if applicable)

## Additional Context

## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have added tests.
- [ ] I have commented my code.
- [ ] I have included a `CHANGELOG.md` entry.
- [ ] I have updated documentation in `github.com:entropyxyz/entropy-docs`, where necessary.

2024-11-14 20:42 UTC, rh0delta commented
this will need updating if #306 is merged before this PR

2024-11-20 03:37 UTC, mixmix requested changes
Changes requested. Looking at the issue that generated this, I see it was under-specified. My/ our bad for having something in up-next like that. 

I think in those cases where we haven't shown expected input/ output, we should write an example first and review that. It's easier/ quicker than building something with no design.

2024-11-20 03:37 UTC, mixmix commented on src/balance/command.ts
> +    .argument('[account]', [
:fire: this changes the `account` argument to "optional" ... but it's only optional in the case that `--all` was passed.
This matters because `commander` normally does some work for us with helpful errors if a user does not supply a `<required>` argument. We can go off-piste, but then we need to build up our own guard rails

2024-11-20 03:37 UTC, mixmix commented on src/balance/command.ts
>      .action(async (account, opts) => {
I don't like this:
- `account` used to be able to be an `address` OR `alias` for an account, you have broken that with `tempAddress`
- there should be only 2 paths through this but you have accidentally made 3:
  - :heavy_check_mark: `entropy balance naynay`  or `entropy balance 123adsd12312312asads987398172bb`
  - :heavy_check_mark: `entropy balance --all`
  - :x: `entropy balance` - this should error. It does not here yet.

Here's how I'd code it

```js
.action(async (account, opts) => {
  if (account) {
    // use old code?
  }
  else if (opts.all) {
    // some new code
  }
  else {
    // write error
    process.exit(1)
  }
})
```

maybe once I'd seen that, then look for ways to refactor

2024-11-20 03:37 UTC, mixmix commented on src/balance/utils.ts
> +export function formattedBalances (balanceInfo: BalanceInfo) {
two questions:
1. we need to decide if we're outputting units on the end of this or not. I'm pretty keen on not. Can be another PR though after we decide finally across the repo.
2. Can this please be an Array?
  It seems silly maybe, but it makes for easier parsing in other scripts (notice how you had to write `Object.keys` for example). It also makes it easier to add more info later, which isn't so easy if you lock in ` { [address]: balance }`

Example solution: 
```js
[
  { address: 'aaaaaaaaaaaaaaaaaaaaaaa', bits: 1.12345688 },
  { address: 'bbbbbbbbbbbbbbbbbbbbbbb', bits: 27.2000013 }
]
```

2024-11-20 03:37 UTC, mixmix commented on src/balance/utils.ts
> +export function formattedBalances (balanceInfo: BalanceInfo) {
re: (2) maybe this is a different issue and we should have a look what we do elsewhere. 

`entropy account ls` uses Array

2024-11-21 20:06 UTC, rh0delta commented on src/balance/command.ts
>      .action(async (account, opts) => {
updated in newest commit

2024-11-21 20:06 UTC, rh0delta commented on src/balance/command.ts
> +    .argument('[account]', [
added pseudo-error handling, whereas instead displaying an error, the help text is displayed

2024-12-03 03:06 UTC, mixmix commented
I'll have a go resolving these

2024-12-03 03:46 UTC, mixmix requested changes
Hey @rh0delta I merged `dev` into this and tweaked functions as I went. This is a sign I'm tired (in merging I was trying to understand the code, so I moved it around to make sure I understood it ) ... not ideal :hankey: sorry

2024-12-03 03:46 UTC, mixmix commented on src/balance/command.ts
> +      }
:fire: this still has a gap: 
```bash
entropy balance naynay -a
```
`!account && opts.all` => `false`
`account` => `true`  but I specified `-a` as well... should not be allowed

So perhaps
```suggestion
      if (!account && opts.all) {
        const tempAddress = accounts[0].address
        entropy = await loadEntropy(tempAddress, opts.endpoint)
      } else if (account && !opts.all) {
        entropy = await loadEntropy(account, opts.endpoint)
      } else {
        balanceCommand.help()
        return process.exit(0)
      }
```

2024-12-03 03:46 UTC, mixmix commented on src/balance/command.ts
> +          })
I refactored this:
- `getBalances` returns an Array => everything is easier to map
- have `balances` output roughly match the `balance` output
   - `[{ account, balance, symbol }]`
   - `{ balance, symbol }`

Perhaps the singular should include the `account` too?

2024-12-10 04:53 UTC, mixmix commented
more merge conflicts @rh0delta

2024-12-11 22:23 UTC, mixmix approved these changes

2024-12-11 22:24 UTC, mixmix commented
I can resolve that

2024-12-11 22:35 UTC, rh0delta commented on src/balance/command.ts
> +    .addOption(configOption())
```suggestion
```

2024-12-11 22:50 UTC, merged