[NayNay] Balance for any address
entropyxyz/cli pull request #315
Opened 2024-11-22 18:40 UTC by rh0delta

## Related Issue(s)

- Resolves #237 

## Proposed Changes

- updated balance for prg cli to be able to retrieve balance for any address
- using newly exposed utility method to getSubstrate from sdk

## Testing

- [x] Unit tests added/updated
- [ ] Integration tests added/updated
- [x] Manual testing performed

## Screenshots (if applicable)

## Additional Context

## Checklist

- [ ] I have performed a self-review of my code.
- [x] I have added tests.
- [x] I have commented my code.
- [ ] I have included a `CHANGELOG.md` entry.
- [ ] I have updated documentation in `github.com:entropyxyz/entropy-docs`, where necessary.

2024-11-22 18:51 UTC, rh0delta commented
Build's will continue to fail for this PR until the addition to the sdk is released.

Re: https://github.com/entropyxyz/sdk/pull/435/files

2024-11-25 23:23 UTC, mixmix commented
@mixmix reviewing this
@frankiebee working on SDK thing for this

2024-12-04 01:14 UTC, mixmix commented on package.json
> +    "@entropyxyz/sdk": "0.4.1-0",
**TODO**: wait for release before merge

2024-12-04 01:25 UTC, mixmix requested changes
Excited for this. Needs more tests to prove it works, and needs to not regress the API

2024-12-04 01:25 UTC, mixmix commented on tests/balance.test.ts
> +
:fire: I'd like to see a test where you use this service to check the balance of e.g. eve and show it's large

2024-12-04 01:25 UTC, mixmix commented on tests/balance.test.ts
> +
:fire: I'd like to see a test for 

```js
EntropyBalance.getAnyBalance(DEFAULT_ENDPOINT, "poop")
```

2024-12-04 01:25 UTC, mixmix commented on src/balance/command.ts
> -      const balance = await BalanceService.getBalance(address)
:fire: no longer supports `entropy balance naynay` - i.e. a breaking change to the API

I'd like to see that supported, and the argument called `<account>` still

2024-12-04 17:49 UTC, rh0delta commented on src/balance/command.ts
> -      const balance = await BalanceService.getBalance(address)
updated balance command to still support config accounts, and changed argument back to account

2024-12-04 19:23 UTC, rh0delta commented on tests/balance.test.ts
> +
add tests

2024-12-10 04:54 UTC, mixmix commented
merge conflicts now here too @rh0delta

2024-12-12 02:21 UTC, mixmix commented
Found some bugs that I fixed in this PR:  https://github.com/entropyxyz/cli/pull/327

2024-12-12 02:23 UTC, mixmix commented
Found that when I have a newly fauceted account this function doesn't work:

```bash
➜  cli git:(mixmix/any-balance) entropy balance --all | jq
[
  {
    "account": "5HNMFB1fELqSAEMkRtUMA6ACs1jD693h16Gt8ixvBS6csJRq",
    "balance": 2,
    "symbol": "BITS"
  },
  {
    "account": "5E4DpqmtnxBA6WbExNvFnJv2Hw5BsUpk8KnAVZLbBMWZVTXb",
    "balance": 0,
    "symbol": "BITS"
  }
]
➜  cli git:(mixmix/any-balance) entropy balance 5HNMFB1fELqSAEMkRtUMA6ACs1jD693h16Gt8ixvBS6csJRq | jq
Provided [account=5HNMFB1fELqSAEMkRtUMA6ACs1jD693h16Gt8ixvBS6csJRq] is not a valid substrate address
```

2024-12-12 02:47 UTC, mixmix commented
yeah have tried with a registered account and still getting that error "not a valid substrate address"

2024-12-12 03:26 UTC, mixmix commented
ok fixed it in that PR : https://github.com/entropyxyz/cli/pull/327/commits/619ff78c3392327f17d323011bd302710b1e26e4

@rh0delta I've seen us slip with if/ else + boolean logic a couple times now. I didn't spot it either till I did some closer testing. I think we need to EITHER write tests over such things, OR try to write much simpler (and more verbose) if/ else if/ else logic. Have a look at the solution in that linked commit. It's more nesting, but more clear (to me at least)

2024-12-16 23:18 UTC, mixmix commented
Mix to re-review

2024-12-17 21:09 UTC, mixmix requested changes
I like this, it's really interesting seeing how little we might need the full SDK... also begs the question "what is it even used for", "what is our policy for when we use SDK and when we use raw substrate?"

I'd like to see us not go to full class methods - I think keeping some of the pattern of `EntropyBase` but making a `SubstrateBase` class that we inherit from will keep the patterns of the repo more coherent and give use support for the logging and other things that we need, tidy up need to pass around `substrate` etc.

Have left more notes and thinking as I went with more detail.
Nice work!

2024-12-17 21:09 UTC, mixmix commented on src/common/substrate-utils.ts
> +    .catch(err => console.error('Error closing connection', err.message))
:fire: I think this should log AND throw ?? like if you don't throw this here swallows the error ... and then what? I think it could cause problems if you expect something to have done it's job and it just doesn't?

2024-12-17 21:09 UTC, mixmix commented on src/balance/main.ts
> +  constructor () {}
perhaps like `EntropyBase` but call it `SubstrateBase`

2024-12-18 22:23 UTC, rh0delta commented on package.json
> +    "@entropyxyz/sdk": "0.4.1-0",
it has not, i believe the full release will come when the signatures stuff is done

2024-12-18 22:32 UTC, rh0delta commented
@mixmix mistakenly made most of the pr updates in this PR https://github.com/entropyxyz/cli/pull/329, so we can merge that into this one once reviewed

2024-12-19 02:03 UTC, mixmix commented on src/account/utils.ts
> +  const account = findAccountByAddressOrName(accounts, accountNameOrAddress || storedConfig.selectedAccount)
@rh0delta can you either make the change or say what your thinking is? (not resolved IMO)

2024-12-19 17:41 UTC, rh0delta commented on src/account/utils.ts
> +  const account = findAccountByAddressOrName(accounts, accountNameOrAddress || storedConfig.selectedAccount)
oh i made this change in the other PR accidentally, which is why i mentioned in our chat to review that one first since it is already being merged into this PR once ready

2024-12-19 17:56 UTC, frankiebee commented on package.json
> +    "@entropyxyz/sdk": "0.4.1-0",
I think it's fine to merge this into dev. I would make this a blocker though for dev -> main

2025-01-08 21:28 UTC, frankiebee commented
> I like this, it's really interesting seeing how little we might need the full SDK... also begs the question "what is it even used for", "what is our policy for when we use SDK and when we use raw substrate?"
> 
you probably asking this because you have'nt needed to deal with signing. The sdk is meant to make signing and the format checking of registering with programs simple.

2025-01-08 21:29 UTC, frankiebee reviewed
Looks good to me thanks for the work!

2025-01-08 21:29 UTC, frankiebee approved these changes

2025-01-08 21:29 UTC, merged