Mixmix/is valid config
entropyxyz/cli pull request #322
Opened 2024-12-05 02:35 UTC by mixmix

The config file is an API for our CLI. This PR adds a validator function which checks the config has all the fields it needs.
This will provide a guard on `config.set` and we'll also use it to check the state of config before ingesting it.

**Note**: the keyring is in flux at the moment so the "accounts" part of the schema is loose-ish - it currently only checks the that an account has `name`, `address`, and that `data.admin` and `data.registration` exist. I forsee this being improved in future PRs

2024-12-10 17:23 UTC, rh0delta approved these changes

2024-12-10 21:01 UTC, rh0delta requested changes
just tested this again, and the config changes are blocking new account creations

```bash
? Select Action Manage Accounts
? interactionChoice: Create/Import Account
? Would you like to import your own seed? No
? name: ttt
file:///Users/nayyirjutha/Development/Entropy/cli/dist/cli.js:3397
  throw new Error("Invalid config", {
        ^

Error: Invalid config
    at assertConfig (file:///Users/nayyirjutha/Development/Entropy/cli/dist/cli.js:3397:9)
    at set (file:///Users/nayyirjutha/Development/Entropy/cli/dist/cli.js:3376:3)
    at selectAndPersistNewAccount (file:///Users/nayyirjutha/Development/Entropy/cli/dist/cli.js:11061:9)
    at async entropyAccount (file:///Users/nayyirjutha/Development/Entropy/cli/dist/cli.js:11169:7)
    at async main (file:///Users/nayyirjutha/Development/Entropy/cli/dist/cli.js:12117:26) {
  [cause]: 'no account had a "name" matching "selectedAccount": 5CyFkW6b8LwC1Q3CeKHTH3Ky8zZJz7VY2MQ2rW3JpXNrdjbE'
}

Node.js v20.10.0
```

2024-12-11 01:42 UTC, mixmix commented
@rh0delta the error was in the code - the `selectedAccount` should have be an `account.name` not `account.address`

I've got the errors listing the cause of the invalid config:
![image](https://github.com/user-attachments/assets/4c3d75d1-9259-443b-b81d-1ddc43ef502d)

It could be there was something in the code where the `selectedAccount` was being set wrong ... in some branch. We may need to make a migration which ensures it's correct?

2024-12-11 01:51 UTC, mixmix commented
I'd be very interested to see your config. Basically you shouldn't even have been able to launch the tui with a bad config

```
➜  cli git:(mixmix/isValidConfig) entropy tui
file:///home/ENTROPY/cli/dist/cli.js:3397
  throw new Error("Invalid config", {
        ^

Error: Invalid config
    at assertConfig (file:///home/ENTROPY/cli/dist/cli.js:3397:9)
    at init (file:///home/ENTROPY/cli/dist/cli.js:3369:5)
    at async Object.callback (file:///home/ENTROPY/cli/dist/cli.js:12414:5)
    at async Command.parseAsync (/home/ENTROPY/cli/node_modules/commander/lib/command.js:1092:5) {
  [cause]: 'no account had a "name" matching "selectedAccount": noo noo'
}
```

2024-12-11 03:50 UTC, mixmix commented
Added a migration which fixes `selectedAccount` thing @rh0delta - and also changes the default "empty" state from `""` to `null` which is waaaaay clearer

2024-12-11 05:00 UTC, mixmix commented on src/config/schema.ts
> +      ].join("")
any string that is 48 characters long, AND uses only characters found in base58.

I think that a real pattern you will find will always start or end with particular padding characters.... so this is not 100% water-tight, but it's sharp enough that it will catch sillies

2024-12-11 22:19 UTC, rh0delta commented
> I'd be very interested to see your config. Basically you shouldn't even have been able to launch the tui with a bad config
> 
> ```
> ➜  cli git:(mixmix/isValidConfig) entropy tui
> file:///home/ENTROPY/cli/dist/cli.js:3397
>   throw new Error("Invalid config", {
>         ^
> 
> Error: Invalid config
>     at assertConfig (file:///home/ENTROPY/cli/dist/cli.js:3397:9)
>     at init (file:///home/ENTROPY/cli/dist/cli.js:3369:5)
>     at async Object.callback (file:///home/ENTROPY/cli/dist/cli.js:12414:5)
>     at async Command.parseAsync (/home/ENTROPY/cli/node_modules/commander/lib/command.js:1092:5) {
>   [cause]: 'no account had a "name" matching "selectedAccount": noo noo'
> }
> ```

my config was not broken when i launched the tui, only became broken after creating a new account

2024-12-11 22:35 UTC, mixmix commented
Welp, let me know if this change fixes it?

Also can you get the tests all still run locally for you on OSX with this branch - I had to add something to get all the tests running now that I've split conifg tests out into a folder

2024-12-12 03:40 UTC, mixmix commented
@rh0delta let me know where this PR is at

Can you re-review + smoke test?

2024-12-12 19:22 UTC, rh0delta approved these changes

2024-12-12 19:34 UTC, merged

2024-12-12 23:14 UTC, mixmix commented on src/account/utils.ts
> -    selectedAccount: newAccount.address
Good catch @rh0delta , thanks!