[NayNay] Signing bug for validators
entropyxyz/cli pull request #63
Opened 2024-06-03 21:20 UTC by rh0delta

- updated signing with adapters to retry the signing request if a specific error is hit as defined in this issue https://github.com/entropyxyz/sdk/issues/367

2024-06-03 22:40 UTC, mixmix requested changes

2024-06-03 22:40 UTC, mixmix commented on src/flows/sign/index.ts
> +let signingAttempts: number = 0
:fire: this is a global variable. The way you're using it means that this function will try fixing once, then it will not be reset to 0 after this signing... so all future buggy signings will be skipped.

This function feels like it's way too fancy, and also not really named what it is. I *\think\* all that we need is for the original code to be the same but like this:

```js
const sigOpts = {
  msg: msgParam,
  order: ['deviceKeyProxy', 'noop'],
}

const signature = await entropy.signWithAdaptersInOrder(sigOpt)
  .catch(err => {
    // HACK: sometimes order is reversed D:
    sigOpts.order.reverse()
    return entropy.signWithAdaptersInOrder(sigOpt)
  })

```

2024-06-03 22:40 UTC, mixmix commented on src/flows/sign/index.ts
> +let signingAttempts: number = 0
NOTE this code assumes `signWithAdaptersInOrder` DOES NOT MUTATE the input... that would need checking.
We should not write functions which mutate inputs though :skull:

2024-06-03 22:40 UTC, mixmix commented on src/flows/sign/index.ts
> +let signingAttempts: number = 0
don't see any mutations, should be fine?

2024-06-03 22:48 UTC, rh0delta commented on src/flows/sign/index.ts
> +let signingAttempts: number = 0
> :fire: this is a global variable. The way you're using it means that this function will try fixing once, then it will not be reset to 0 after this signing... so all future buggy signings will be skipped.
> 
> 
> 
> This function feels like it's way too fancy, and also not really named what it is. I *\think\* all that we need is for the original code to be the same but like this:
> 
> 
> 
> ```js
> 
> const sigOpts = {
> 
>   msg: msgParam,
> 
>   order: ['deviceKeyProxy', 'noop'],
> 
> }
> 
> 
> 
> const signature = await entropy.signWithAdaptersInOrder(sigOpt)
> 
>   .catch(err => {
> 
>     // HACK: sometimes order is reversed D:
> 
>     sigOpts.order.reverse()
> 
>     return entropy.signWithAdaptersInOrder(sigOpt)
> 
>   })
> 
> 
> 
> ```

We could do this way of catching the error, but we still need to keep track of the attempts made to signing and handle accordingly. I find the try..catch to be cleaner, thoughts?

2024-06-04 15:04 UTC, rh0delta commented
@mixmix ready for re-review

2024-06-05 18:13 UTC, frankiebee commented on src/flows/sign/index.ts
> +      // }
is this needed?

2024-06-05 18:14 UTC, frankiebee commented on src/flows/sign/index.ts
> +    //   message: 'Enter the path to the file you wish to sign:',
whats this for?

2024-06-05 23:11 UTC, mixmix commented on src/flows/sign/index.ts
> +let signingAttempts: number = 0
- `try` / `catch` is the same as `promise.catch` :shrug: (don't mind)
- your global variable is still a liability - if multiple people are calling this function your global variable becomes a race condition

You need to change this to not use it - either the way I suggested, or pass the attempts count as an argument

```js
async function signWithAdaptersInOrder (entropy, signingData, attempts = 0) {
  if (attempt > 1) throw Error('NOPE')
  // ...


  signWithAdaptersInOrder(entropy, signingData, attempt + 1)
}
```

2024-06-06 00:09 UTC, mixmix commented
@rh0delta that :fire: is still an issue. I've added more context why it's dangerous
https://github.com/entropyxyz/cli/pull/63/files#r1628548871

2024-06-06 04:06 UTC, rh0delta commented
@mixmix this is ready for re-review. I followed your idea of passing in the signing attempts, but rather than having the check for the number of attempts at the top, I've added it to the conditional for retrying the signing request with the shuffled order

2024-06-12 01:31 UTC, mixmix approved these changes

2024-06-12 01:43 UTC, merged