CLI base
entropyxyz/cli pull request #91
Opened 2024-06-11 04:26 UTC by mixmix

This PR adds:
- **compling** (ts => js)
    - I have copied the sdk setup 
    - I wasted time trying something new. we should come back and update this when we figure out a beautiful TS pattern
- **commander**, which captures CLI input and will allow us to add programmatic functions nicely
- deletes some unused `questions.ts` file

2024-06-11 04:27 UTC, mixmix commented on package.json
> -    "viem": "^2.7.8",
`viem` was causing problems with compiling. Not even used atm

2024-06-11 16:53 UTC, rh0delta approved these changes
this looks good to me, @frankiebee do you want to give it a once over too?

2024-06-11 20:24 UTC, frankiebee commented on package.json
> +  "type": "module",
is this needed?

2024-06-11 20:57 UTC, frankiebee requested changes

2024-06-11 20:57 UTC, frankiebee commented on package.json
> +  ],
lets add `entropy protocol` here

2024-06-11 20:57 UTC, frankiebee commented on src/common/ascii.ts
> +                                                      @@@@@@     COREv0.0.12
this is incorrect should be `0.1.0`

2024-06-11 20:57 UTC, frankiebee commented on src/common/ascii.ts
> +                                                      @@@@@@     COREv0.0.12
side note for sdk: make this exportable?

2024-06-11 20:57 UTC, frankiebee commented on tsconfig.json
> +      "substrate-generated-types/interfaces"
not needed

```suggestion
```

2024-06-11 20:57 UTC, frankiebee commented on tsconfig.json
> +    "old",
not needed
```suggestion
```

2024-06-11 20:57 UTC, frankiebee commented on tsconfig.json
> +    "substrate-generated-types"
not needed

```suggestion
```

2024-06-11 22:54 UTC, mixmix commented on package.json
> +  "type": "module",
TODO: later :eyes:

2024-06-11 23:19 UTC, rh0delta commented on src/common/ascii.ts
> +                                                      @@@@@@     COREv0.0.12
The versioning for core is fixed in a branch that I have, it's one of the issues I took care of this morning

2024-06-12 02:35 UTC, mixmix commented
@frankiebee this is ready for sign off. This Changes Requested :lock: is both good and annoying :japanese_ogre:

2024-06-12 16:55 UTC, rh0delta approved these changes
minor change in readme, otherwise it looks good

2024-06-12 16:55 UTC, rh0delta commented on README.md
> +> :warning: This tool is early development. As such, a lot of things do not work. Feel free to play around with it and report any issues at [github.com/entropyxyz/cli](https://github.com/entropyxyz/c
```suggestion
> :warning: This tool is in early development. As such, a lot of things do not work. Feel free to play around with it and report any issues at [github.com/entropyxyz/cli](https://github.com/entropyxyz/cli).
```

2024-06-12 21:30 UTC, merged